// flashcards-react/src/components/modals/set/delete-set-confirmation-modal/delete-set-confirmation-modal.tsx
import React from 'react';
import styles from './delete-set-confirmation-modal.module.css';
import { deleteSet } from '../../../../services/set-service';

interface DeleteSetConfirmationModalProps {
    closeDeleteSetModal: () => void;
    refreshSetsList: () => void;
    setObj: {
        setId: string;
        setName: string;
    };
}

const DeleteSetConfirmationModal: React.FC<DeleteSetConfirmationModalProps> = ({ closeDeleteSetModal, refreshSetsList, setObj }) => {

    const handleDelete = async () => {
        try {
            await deleteSet(setObj.setId);
            refreshSetsList();
            closeDeleteSetModal();
        } catch (error) {
            console.error(error);
        }
    };

    return (
        <>
            <div className={styles.overlay} onClick={closeDeleteSetModal}></div>
            <div className={styles.deleteSetModalContainer}>
                <div className={styles.header}>Usuwanie zbioru</div>
                <div className={styles.content}>
                    Czy na pewno chcesz usunąć zbiór <i>{setObj.setName}</i>?
                </div>
                <div className={styles.actions}>
                    <button onClick={handleDelete} className={styles.btnCustom}>Usuń</button>
                    <button onClick={closeDeleteSetModal} className={styles.cancelBtn}>Anuluj</button>
                </div>
            </div>
        </>
    );
};

export default DeleteSetConfirmationModal;

// flashcards-angular/src/app/components/modals/set/delete-set-confirmation-modal/delete-set-confirmation-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SetService } from 'src/app/services/set.service';

@Component({
  selector: 'app-delete-set-confirmation-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './delete-set-confirmation-modal.component.html',
  styleUrls: ['./delete-set-confirmation-modal.component.css']
})
export class DeleteSetConfirmationModalComponent {
  @Input() setObj: any;
  @Output() onDelete = new EventEmitter(); 
  @Output() onDeleteCancel = new EventEmitter();
  
  constructor(public setService: SetService) { }

  deleteSet() {
    this.setService.deleteSet(this.setObj.setId).subscribe({
      next: (res) => {
        this.setService.showDeleteSetConfirmationModal = false;
        this.onDelete.emit();
        console.log("Set deleted successfully");
      },
      error: (err) => {
        console.log(err);
      }
    });
  }

  deleteCancelAction() {
    console.log("CANCEL");
    this.onDeleteCancel.emit();
    this.setService.showDeleteSetConfirmationModal=false;
  }
}

<div id="overlay" (click)="deleteCancelAction()"></div>
<div id="container">
    <div id="header">Usuwanie zbioru</div>
    <div id="content">
        Czy na pewno chcesz usunąć zbiór <i>{{ setObj.setName }}</i>?
    </div>
    <div id="actions">
        <button (click)="deleteSet()" class="btn btn-custom">Usuń</button>

        <button (click)="deleteCancelAction()" class="cancel btn">Anuluj</button>
    </div>
</div>
