// flashcards-react/src/components/modals/set/update-set-modal/update-set-modal.tsx
import React from 'react';
import { useForm } from 'react-hook-form';
import styles from './update-set-modal.module.css';
import { updateSet } from '../../../../services/set-service';

interface FormValues {
    setName: string;
}

interface UpdateSetModalProps {
    closeUpdateSetModal: () => void;
    refreshSetsList: () => void;
    setObj: {
        setId: string;
        setName: string;
    };
}

const UpdateSetModal: React.FC<UpdateSetModalProps> = ({ closeUpdateSetModal, refreshSetsList, setObj }) => {
    const { register, handleSubmit, formState: { errors, dirtyFields, touchedFields }, setError, clearErrors } = useForm<FormValues>({
        mode: 'onChange',
    });

    const validateSetName = (value: string) => {
        if (!value.trim()) {
            setError('setName', { type: 'manual', message: '*Pole jest wymagane.' });
        } else {
            clearErrors('setName');
        }
    };

    const onSubmit = async (data: FormValues) => {
        try {
            await updateSet({
                setId: setObj.setId,
                setName: data.setName
            });
            refreshSetsList();
            closeUpdateSetModal();
        } catch (error) {
            console.error(error);
        }
    };

    const isSubmitButtonDisabled = () => {
        return !!errors.setName || !dirtyFields.setName;
    };

    return (
        <>
            <div className={styles.overlay} onClick={closeUpdateSetModal}></div>
            <div className={styles.updateSetModalcontainer}>
                <div className={styles.header}>Edycja zbioru</div>
                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className={styles.content}>
                        <div className={styles.field}>
                            <input
                                type="text"
                                id="setName"
                                className={styles.setName}
                                placeholder={setObj.setName}
                                {...register('setName', {
                                    required: '*Pole jest wymagane.',
                                    onChange: (e) => validateSetName(e.target.value),
                                    onBlur: (e) => validateSetName(e.target.value)
                                })}
                            />
                            {errors.setName && (touchedFields.setName || dirtyFields.setName) && (
                                <span className="formError">{errors.setName.message}</span>
                            )}
                        </div>
                    </div>
                    <div className={styles.actions}>
                        <button type="submit" className={styles.btnCustom} disabled={isSubmitButtonDisabled()}>
                            Zatwierdź
                        </button>
                        <button type="button" className={styles.cancelBtn} onClick={closeUpdateSetModal}>
                            Anuluj
                        </button>
                    </div>
                </form>
            </div>
        </>
    );
};

export default UpdateSetModal;

// flashcards-angular/src/app/components/modals/set/update-set-modal/update-set-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { SetService } from 'src/app/services/set.service';

@Component({
  selector: 'app-update-set-modal',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule
  ],
  templateUrl: './update-set-modal.component.html',
  styleUrls: ['./update-set-modal.component.css']
})
export class UpdateSetModalComponent {
  @Input() setObj: any;
  @Output() onUpdate = new EventEmitter(); 
  updateSetForm!: FormGroup;

  constructor(
    public setService: SetService,
    private formBuilder: FormBuilder
  ){}

  ngOnInit(): void {
    this.updateSetForm = this.formBuilder.group({
      setName: ['', Validators.required],
      setId: this.setObj.setId
    });
  }

  updateSet() {
    this.setService.updateSet(this.updateSetForm.value)
    .subscribe({
      next: (res) => {
        this.setService.showUpdateSetModal = false;
        this.onUpdate.emit();
      },
      error: (err) => {
        console.log(err);
      }
    });
  }
  closeAddModal() {
    this.setService.showUpdateSetModal = false;
  }
}

<div id="overlay" (click)="closeAddModal()"></div>
<div id="container">
    <div id="header">Edycja zbioru</div>
    <form [formGroup]="updateSetForm" (ngSubmit)="updateSet()">
        <div id="content">
            <div class="field">
                <input type="text" id="setName" formControlName="setName" placeholder="{{setObj.setName}}">
                <span *ngIf="updateSetForm.controls['setName'].errors?.['required'] && (updateSetForm.controls['setName'].dirty || updateSetForm.controls['setName'].touched)">
                    Pole jest wymagane.
                </span>
            </div>
        </div>
        <div id="actions">
            <button type="submit" class="btn btn-custom" [disabled]="!updateSetForm.valid">Zatwierdź</button>
            <button type="button" class="cancel btn" (click)="closeAddModal()">Anuluj</button>
        </div>
    </form>
</div>
