// flashcards-react/src/components/single-set/single-set.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import styles from './single-set.module.css';

interface Set {
    setId: string;
    setName: string;
    createdAt: string;
    updatedAt: string;
    flashcardCount: number;
}

interface Props {
    setObj: Set;
    onDelete: () => void; 
}

const formatDate = (dateString?: string) => {
    if (!dateString) {
        return '-'; 
    }
    const date = new Date(dateString);
    if (isNaN(date.getTime())) {
        return '-'; 
    }
    const day = date.getDate().toString().padStart(2, '0');
    const month = (date.getMonth() + 1).toString().padStart(2, '0');
    const year = date.getFullYear();
    const hours = date.getHours().toString().padStart(2, '0');
    const minutes = date.getMinutes().toString().padStart(2, '0');

    return `${hours}:${minutes} ${day}.${month}.${year}`;
};


const SingleSetComponent: React.FC<Props> = ({ setObj, onDelete }) => {
    const navigate = useNavigate();

    const navigateToSetDetails = () => {
        navigate(`/sets/${setObj.setId}/flashcards`);
    };

    const editSet = () => {
        navigate(`/edit-set/${setObj.setId}`);
    };

    const deleteSet = () => {
        console.log("Delete set" + JSON.stringify(setObj));
        onDelete();
    };

    return (
        <div className={styles.setContainer}>
            <div className={styles.setHeader}>
                <h2>{setObj.setName}</h2>
            </div>
            <div className={styles.setDetails}>
                <p>Data utworzenia: {formatDate(setObj.createdAt)}</p>
                <p>Data modyfikacji: {setObj.updatedAt ? formatDate(setObj.updatedAt) : '-'}</p>
                <p>Liczba fiszek: {setObj.flashcardCount}</p>
            </div>
            <div className={styles.setActions}>
                <button onClick={navigateToSetDetails}>Zobacz</button>
                <button onClick={editSet}>Edytuj</button>
                <button onClick={deleteSet}>Usuń</button>
            </div>
        </div>
    );
    
};

export default SingleSetComponent;

// flashcards-angular/src/app/components/single-set/single-set.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { SetService } from 'src/app/services/set.service';
import { DeleteSetConfirmationModalComponent } from '../modals/set/delete-set-confirmation-modal/delete-set-confirmation-modal.component';

@Component({
  selector: 'app-single-set',
  standalone: true,
  imports: [CommonModule, DeleteSetConfirmationModalComponent],
  templateUrl: './single-set.component.html',
  styleUrls: ['./single-set.component.css'],
  providers: [SetService]
})
export class SingleSetComponent {
  @Input() setObj: any;
  @Output() onDelete = new EventEmitter<void>(); 
  @Output() onDeleteCancel = new EventEmitter<void>(); 

  constructor(
    public setService: SetService,
    private router: Router
  ) {
  }

  navigateToSetDetails(setId: number) {
    this.router.navigate(['/sets', setId, 'flashcards']);
  }
  

  editSet(setId: number) {
    this.router.navigate(['/edit-set', setId]);
  }

  deleteSet(setObj: any) {
    console.log("Delete set" + JSON.stringify(setObj));
    this.setService.showDeleteSetConfirmationModal = true;
  }

  deleteCancelAction() {
    this.setService.showDeleteSetConfirmationModal = false;
  }
}

<div class="set-container">
    <div class="set-header">
        <h2>{{ setObj.setName }}</h2>
    </div>
    <div class="set-details">
        <p>Data utworzenia: {{ setObj.createdAt | date:'HH:mm dd.MM.yyyy'}}</p>
        <p>Data modyfikacji: {{ (setObj.updatedAt | date:'HH:mm dd.MM.yyyy' ) || '-' }}</p>
        <p>Liczba fiszek: {{ setObj.flashcardCount }}</p>
    </div>
    <div class="set-actions">
        <button (click)="navigateToSetDetails(setObj.setId)">Zobacz</button>
        <button (click)="editSet(setObj.setId)">Edytuj</button>
        <button (click)="deleteSet(setObj)">Usuń</button>
    </div>
</div>
<app-delete-set-confirmation-modal *ngIf="setService.showDeleteSetConfirmationModal === true" [setObj]="setObj" (onDelete)="onDelete.emit()" (onDeleteCancel)="onDeleteCancel.emit()"></app-delete-set-confirmation-modal>
