// flashcards-react/src/components/modals/flashcard/update-flashcard-modal/update-flashcard-modal.tsx
import React from 'react';
import { useForm } from 'react-hook-form';
import styles from './update-flashcard-modal.module.css'; 
import { updateFlashcard } from '../../../../services/flashcard-service'; 

interface FormValues {
    front: string;
    back: string;
}

interface UpdateFlashcardModalProps {
    closeUpdateFlashcardModal: () => void;
    refreshFlashcardsList: () => void;
    flashcardObj: {
        flashcardId: string;
        front: string;
        back: string;
    };
}

const UpdateFlashcardModal: React.FC<UpdateFlashcardModalProps> = ({ closeUpdateFlashcardModal, refreshFlashcardsList, flashcardObj }) => {
    const { register, handleSubmit, formState: { errors, touchedFields, dirtyFields }, setError, clearErrors } = useForm<FormValues>({
        mode: 'onChange'
    });

    const validateField = (field: 'front' | 'back', value: string) => {
        if (!value.trim()) {
            setError(field, { type: 'manual', message: '*Pole jest wymagane.' });
        } else {
            clearErrors(field);
        }
    };

    const onSubmit = async (data: FormValues) => {
        try {
            await updateFlashcard({
                flashcardId: flashcardObj.flashcardId, 
                front: data.front,
                back: data.back
            });
            refreshFlashcardsList();
            closeUpdateFlashcardModal(); 
        } catch (error) {
            console.log(error);
        }
    };

    const isSubmitButtonDisabled = () => {
        return !!errors.front || !!errors.back || !dirtyFields.front || !dirtyFields.back;
    };

    return (
        <>
            <div className={styles.updateFlashcardModalOverlay} onClick={closeUpdateFlashcardModal}></div>
            <div className={styles.updateFlashcardModalContainer}>
                <div className={styles.header}>Edytowanie fiszki</div>
                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className={styles.content}>
                        <div className={styles.field}>
                            <input
                                type="text"
                                id="front"
                                className={styles.input}
                                placeholder={flashcardObj.front}
                                {...register('front', {
                                    required: '*Pole jest wymagane.',
                                    onChange: (e) => validateField('front', e.target.value),
                                    onBlur: (e) => validateField('front', e.target.value)
                                })}
                            />
                            {errors.front && (touchedFields.front || dirtyFields.front) && (
                                <span className="formError">{errors.front.message}</span>
                            )}
                        </div>
                        <div className={styles.field}>
                            <input
                                type="text"
                                id="back"
                                className={styles.input}
                                placeholder={flashcardObj.back}
                                {...register('back', {
                                    required: '*Pole jest wymagane.',
                                    onChange: (e) => validateField('back', e.target.value),
                                    onBlur: (e) => validateField('back', e.target.value)
                                })}
                            />
                            {errors.back && (touchedFields.back || dirtyFields.back) && (
                                <span className="formError">{errors.back.message}</span>
                            )}
                        </div>
                    </div>
                    <div className={styles.actions}>
                        <button type="submit" disabled={isSubmitButtonDisabled()}>
                            Zatwierdź
                        </button>
                        <button type="button" onClick={closeUpdateFlashcardModal}>
                            Anuluj
                        </button>
                    </div>
                </form>
            </div>
        </>
    );
};

export default UpdateFlashcardModal;

// flashcards-angular/src/app/components/modals/flashcard/update-flashcard-modal/update-flashcard-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { FlashcardService } from 'src/app/services/flashcard.service';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-update-flashcard-modal',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './update-flashcard-modal.component.html',
  styleUrls: ['./update-flashcard-modal.component.css']
})
export class UpdateFlashcardModalComponent {
  @Input() flashcardObj: any;
  @Output() onUpdate = new EventEmitter(); 
  updateFlashcardForm!: FormGroup;
  constructor(
    public flashcardService: FlashcardService,
    private formBuilder: FormBuilder,
    private activatedRoute: ActivatedRoute
  ){}

  ngOnInit(): void {
    this.updateFlashcardForm = this.formBuilder.group({
      flashcardId: this.flashcardObj.flashcardId,
      front: ['', Validators.required],
      back: ['', Validators.required],
      setId: [this.activatedRoute.snapshot.params['setId'], Validators.required]
    });
  }

  updateFlashcard() {
    this.flashcardService.updateFlashcard(this.updateFlashcardForm.value)
    .subscribe({
      next: (res) => {
        this.flashcardService.showUpdateFlashcardModal = false;
        this.onUpdate.emit();
      },
      error: (err) => {
        console.log(err);
      }
    });
  }

  closeUpdateModal() {
    this.flashcardService.showUpdateFlashcardModal = false;
  }
}

<div id="overlay" (click)="closeUpdateModal()"></div>
<div id="container">
    <div id="header">Edytowanie fiszki</div>
    <form [formGroup]="updateFlashcardForm" (ngSubmit)="updateFlashcard()">
        <div id="content">
            <div class="field">
                <input type="text" id="front" formControlName="front" placeholder="{{flashcardObj.front}}">
                <span *ngIf="updateFlashcardForm.controls['front'].errors?.['required'] && (updateFlashcardForm.controls['front'].dirty || updateFlashcardForm.controls['front'].touched)">
                    Pole jest wymagane.
                </span>
            </div>
            <div class="field">
                <input type="text" id="back" formControlName="back" placeholder="{{flashcardObj.back}}">
                <span *ngIf="updateFlashcardForm.controls['back'].errors?.['required'] && (updateFlashcardForm.controls['back'].dirty || updateFlashcardForm.controls['back'].touched)">
                    Pole jest wymagane.
                </span>
            </div>
        </div>
        <div id="actions">
            <button type="submit" class="btn btn-custom" [disabled]="!updateFlashcardForm.valid">Zatwierdź</button>
            <button type="button" class="cancel btn" (click)="closeUpdateModal()">Anuluj</button>
        </div>
    </form>
</div>
