// flashcards-angular/src/app/components/modals/flashcard/add-flashcard-modal/add-flashcard-modal.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { FlashcardService } from 'src/app/services/flashcard.service';

@Component({
  selector: 'app-add-flashcard-modal',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './add-flashcard-modal.component.html',
  styleUrls: ['./add-flashcard-modal.component.css']
})
export class AddFlashcardModalComponent implements OnInit{
  @Output() onAdd = new EventEmitter(); 
  addFlashcardForm!: FormGroup;
  constructor(
    public flashcardService: FlashcardService,
    private formBuilder: FormBuilder,
    private activatedRoute: ActivatedRoute
  ){}

  ngOnInit(): void {
    this.addFlashcardForm = this.formBuilder.group({
      setId: [this.activatedRoute.snapshot.params['setId'], Validators.required],
      front: ['', Validators.required],
      back: ['', Validators.required]
    });
  }

  addFlashcard() {
    this.flashcardService.addFlashcard(this.addFlashcardForm.value).subscribe({
      next: (res) => {
        this.flashcardService.showAddFlashcardModal = false;
        this.onAdd.emit();
      },
      error: (err) => {
        console.log(err);
      }
    });
  }
  closeAddModal() {
    this.flashcardService.showAddFlashcardModal = false;
  }
}

<div id="overlay" (click)="closeAddModal()"></div>
<div id="container">
    <div id="header">Dodawanie fiszki</div>
    <form [formGroup]="addFlashcardForm" (ngSubmit)="addFlashcard()">
        <div id="content">
            <div class="field">
                <!-- <label for="front">Przód fiszki:</label> -->
                <input type="text" id="front" formControlName="front" placeholder="Przód fiszki">
                <span *ngIf="addFlashcardForm.controls['front'].errors?.['required'] && (addFlashcardForm.controls['front'].dirty || addFlashcardForm.controls['front'].touched)">
                    Pole jest wymagane.
                </span>
            </div>
            <div class="field">
                <!-- <label for="back">Tył fiszki:</label> -->
                <input type="text" id="back" formControlName="back" placeholder="Tył fiszki">
                <span *ngIf="addFlashcardForm.controls['back'].errors?.['required'] && (addFlashcardForm.controls['back'].dirty || addFlashcardForm.controls['back'].touched)">
                    Pole jest wymagane.
                </span>
            </div>
        </div>
        <div id="actions">
            <button type="submit" class="btn btn-custom" [disabled]="!addFlashcardForm.valid">Dodaj fiszkę</button>
            <button type="button" class="cancel btn" (click)="closeAddModal()">Anuluj</button>
        </div>
    </form>
</div>

// flashcards-react/src/components/modals/flashcard/add-flashcard-modal/add-flashcard-modal.tsx
import React from 'react';
import { useForm } from 'react-hook-form';
import styles from './add-flashcard-modal.module.css'; 
import { addFlashcard } from '../../../../services/flashcard-service';
import { useParams } from 'react-router-dom';

interface FormValues {
    front: string;
    back: string;
}

interface AddFlashcardModalProps {
    closeAddFlashcardModal: () => void;
    refreshFlashcardList: () => void;
}

const AddFlashcardModal: React.FC<AddFlashcardModalProps> = ({ closeAddFlashcardModal, refreshFlashcardList }) => {
    const { setId } = useParams();
    const { register, handleSubmit, formState: { errors, touchedFields, dirtyFields }, setError, clearErrors } = useForm<FormValues>({
        mode: 'onChange',
    });
    

    const validateField = (field: 'front' | 'back', value: string) => {
        if (!value.trim()) {
            setError(field, { type: 'manual', message: '*Pole jest wymagane.' });
        } else {
            clearErrors(field);
        }
    };

    const onSubmit = async (data: FormValues) => {
        try {
            await addFlashcard({
                setId: setId,
                front: data.front,
                back: data.back
            });
            refreshFlashcardList();
            closeAddFlashcardModal();
        } catch (error) {
            console.log(error);
        }
    };

    const isSubmitButtonDisabled = () => {
        return !!errors.front || !!errors.back || !dirtyFields.front || !dirtyFields.back;
    };

    return (
        <>
            <div className={styles.addFlashcardModalOverlay} onClick={closeAddFlashcardModal}></div>
            <div className={styles.addFlashcardModalContainer}>
                <div className={styles.header}>Dodawanie fiszki</div>
                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className={styles.content}>
                        <div className={styles.field}>
                            <input
                                type="text"
                                id="front"
                                className={styles.input}
                                placeholder="Przód fiszki"
                                {...register('front', {
                                    required: '*Pole jest wymagane.',
                                    onChange: (e) => validateField('front', e.target.value),
                                    onBlur: (e) => validateField('front', e.target.value)
                                })}
                            />
                            {errors.front && (touchedFields.front || dirtyFields.front) && (
                                <span className="formError">{errors.front.message}</span>
                            )}
                        </div>
                        <div className={styles.field}>
                            <input
                                type="text"
                                id="back"
                                className={styles.input}
                                placeholder="Tył fiszki"
                                {...register('back', {
                                    required: '*Pole jest wymagane.',
                                    onChange: (e) => validateField('back', e.target.value),
                                    onBlur: (e) => validateField('back', e.target.value)
                                })}
                            />
                            {errors.back && (touchedFields.back || dirtyFields.back) && (
                                <span className="formError">{errors.back.message}</span>
                            )}
                        </div>
                    </div>
                    <div className={styles.actions}>
                        <button type="submit" disabled={isSubmitButtonDisabled()}>
                            Dodaj fiszkę
                        </button>
                        <button type="button" onClick={closeAddFlashcardModal}>
                            Anuluj
                        </button>
                    </div>
                </form>
            </div>
        </>
    );
};

export default AddFlashcardModal;
