// flashcards-react/src/components/modals/learn/learning-finished-modal/learning-finished-modal.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import styles from './learning-finished-modal.module.css'; 

const LearningFinishedModal = () => {
    const navigate = useNavigate(); 

    const navigateToSets = () => {
        navigate(`/sets`); 
    };

    const continueLearning = () => {
        navigate(0);
    };

    return (
        <>
            <div className={styles.learningOverlay}></div>
            <div className={styles.learningFinishedModalContainer}>
                <div className={styles.header}>Gratulacje!</div>
                <div className={styles.content}>
                Ukończyłeś naukę wszystkich fiszek w tym zbiorze!
                </div>
                <div className={styles.actions}>
                    <button onClick={continueLearning}>Kontynuuj naukę</button>
                    <button onClick={navigateToSets}>Do zbiorów</button>
                </div>
            </div>
        </>
    );
};

export default LearningFinishedModal;

// flashcards-angular/src/app/components/modals/learn/learning-finished-modal/learning-finished-modal.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-learning-finished-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './learning-finished-modal.component.html',
  styleUrls: ['./learning-finished-modal.component.css']
})
export class LearningFinishedModalComponent {

  constructor(private router: Router) {

  }

  continueLearning() {
    const currentUrl = this.router.url;
    this.router.navigateByUrl('/', { skipLocationChange: true }).then(() => {
      this.router.navigate([currentUrl]); 
    });
  }
  moveToSets() {
    this.router.navigate(['/sets']);
  }
}

<div id="overlay"></div>
<div id="container">
    <div id="header">Gratulacje!</div>
    <div id="content">
        Ukończyłeś naukę wszystkich fiszek w tym zbiorze!
    </div>
    <div id="actions">
        <button class="btn btn-custom" (click)="continueLearning()">Kontynuuj naukę</button>
        <button class="btn" (click)="moveToSets()">Do zbiorów</button>
    </div>
</div>
