// flashcards-react/src/pages/learn/learn.tsx
import { useState, useEffect } from 'react';
import Navbar from '../../components/navbar/navbar';
import styles from './learn.module.css';
import LearningFinishedModal from '../../components/modals/learn/learning-finished-modal/learning-finished-modal';
import { useParams } from 'react-router-dom';
import { getAllFlashcardsBySetId } from '../../services/set-service';

interface Flashcard {
  front: string;
  back: string;
  learned: boolean;
}

const LearnComponent = () => {
  const { setId } = useParams();
  const [allFlashcards, setAllFlashcards] = useState<Flashcard[]>([]);
  const [totalNumberOfFlashcards, setTotalNumberOfFlashcards] = useState(0);
  const [currentFlashcardIndex, setCurrentFlashcardIndex] = useState(0);
  const [correctAnswers, setCorrectAnswers] = useState(0);
  const [incorrectAnswers, setIncorrectAnswers] = useState(0);
  const [showLearningFinishedModal, setShowLearningFinishedModal] = useState(false);


  useEffect(() => {
    remainingCards();
  }, []);

  useEffect(() => {
    if (setId) {  
      fetchFlashcards(setId); 
    }
  }, [setId]);

  const fetchFlashcards = async (id: string) => {
    try {
      let fetchedFlashcards = await getAllFlashcardsBySetId(id); 
      fetchedFlashcards = fetchedFlashcards.map((flashcard: Flashcard) => ({ ...flashcard, learned: false }));
      setAllFlashcards(fetchedFlashcards); 
      setTotalNumberOfFlashcards(fetchedFlashcards.length);
    } catch (error) {
      console.error("Error fetching flashcards:", error); 
    }
  };

  const getNextFlashcard = () => {
    if (currentFlashcardIndex < allFlashcards.length - 1) {
      setCurrentFlashcardIndex(currentFlashcardIndex + 1);
    } else {
      const incorrectFlashcards = allFlashcards.filter(flashcard => !flashcard.learned);
      if (incorrectFlashcards.length === 0) {
        setShowLearningFinishedModal(true);
      } else {
        setAllFlashcards(incorrectFlashcards);
        setCurrentFlashcardIndex(0);
      }
    }
  };

  const answerFlashcard = (isCorrect: boolean) => {
    const currentFlashcard = allFlashcards[currentFlashcardIndex];

    if (isCorrect) {
      currentFlashcard.learned = true;
      setCorrectAnswers(correctAnswers + 1);
    } else {
      setIncorrectAnswers(incorrectAnswers + 1);
    }

    getNextFlashcard();
  };

  const remainingCards = () => {
    return allFlashcards.filter(flashcard => !flashcard.learned).length;
  };

  return (
    <>
      <Navbar />
      <div className={styles.learnContainer}>
        <p>Do nauczenia: {remainingCards()} / {totalNumberOfFlashcards}</p>
        <div className={styles.container}>
          <div className={styles.card}>
            <div className={styles.front}>
              <p>{allFlashcards[currentFlashcardIndex]?.front}</p>
            </div>
            <div className={styles.back}>
              <p>{allFlashcards[currentFlashcardIndex]?.back}</p>
            </div>
          </div>
        </div>

        <div className={styles.response}>
          <button className={styles.knowButton} onClick={() => answerFlashcard(true)}>
            Znam
          </button>
          <button className={styles.unknownButton} onClick={() => answerFlashcard(false)}>
            Nie wiem
          </button>
        </div>

        <div className={styles.results}>
          <div className={styles.correct}>
            <i className="fa-solid fa-check"></i>
            {correctAnswers}
          </div>
          <div className={styles.incorrect}>
            <i className="fa-solid fa-xmark"></i>
            {incorrectAnswers}
          </div>
        </div>
      </div>
      {showLearningFinishedModal && <LearningFinishedModal />}
    </>
  );
};

export default LearnComponent;

// flashcards-angular/src/app/pages/learn/learn.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SetService } from 'src/app/services/set.service';
import { LearningFinishedModalComponent } from 'src/app/components/modals/learn/learning-finished-modal/learning-finished-modal.component';
import { ActivatedRoute } from '@angular/router';
import { NavbarComponent } from 'src/app/components/navbar/navbar.component';

@Component({
  selector: 'app-learn',
  standalone: true,
  imports: [
    CommonModule, 
    NavbarComponent,
    LearningFinishedModalComponent
  ],
  templateUrl: './learn.component.html',
  styleUrls: ['./learn.component.css'],
  providers: [SetService]
})
export class LearnComponent {
  allFlashcards: Array<any> = [];

  totalFlashcards: number = 0;
  currentFlashcardIndex: number = 0; 
  correctAnswers: number = 0;
  incorrectAnswers: number = 0;


  constructor(
    public setService: SetService,
    private activatedRoute: ActivatedRoute
  ) {
    this.activatedRoute.paramMap.subscribe(params => {
      const setId = params.get('setId'); 
      if (setId) {
        this.getAllFlashcardsBySetId(setId); 
      }
    });
  }

  getAllFlashcardsBySetId(userId: string) {
    this.setService.getAllFlashcardsBySetId(userId)
    .subscribe({
      next: (res) => {
        this.allFlashcards = res.map((flashcard: any) => ({ ...flashcard, learned: false }));
        this.totalFlashcards = this.allFlashcards.length; 
      },
      error: (err) => {
        console.log(err);
      }
    });
  }

  getNextFlashcard() {
    if (this.currentFlashcardIndex < this.allFlashcards.length - 1) {
      this.currentFlashcardIndex++;
    } else {
      const incorrectFlashcards = this.allFlashcards.filter(flashcard => !flashcard.learned);
      if (incorrectFlashcards.length === 0) {
        this.setService.showLearningFinishedModal = true;
      } else {
        this.allFlashcards = [...incorrectFlashcards];
        this.currentFlashcardIndex = 0;
      }
    }
  }

  answerFlashcard(isCorrect: boolean) {
    const currentFlashcard = this.allFlashcards[this.currentFlashcardIndex];
    if (isCorrect) {
      currentFlashcard.learned = true;
      this.correctAnswers++;
    } else {
      this.incorrectAnswers++; 
    }
    this.getNextFlashcard();
  }

  get remainingCards() {
    return this.allFlashcards.filter(f => !f.learned).length;
  }
}

<app-navbar></app-navbar>
<div class="main-container">
    <p>Do nauczenia: {{ remainingCards  }} / {{ totalFlashcards }}</p>
    <div class="container">
        <div class="card">
            <div class="front">
                <p>
                    {{ allFlashcards[currentFlashcardIndex]?.front }}
                </p>
            </div>
            <div class="back">
                <p>{{ allFlashcards[currentFlashcardIndex]?.back }}</p>
            </div>
        </div>
    </div>
    
    <div class="response">
        <button class="know-button" (click)="answerFlashcard(true)">
            Znam
        </button>
        <button class="unknown-button" (click)="answerFlashcard(false)">
            Nie wiem
        </button>
    </div>
    
    <div class="results">
        <div class="correct">
            <i class="fa-solid fa-check"></i>
            {{ correctAnswers }}
        </div>
        <div class="incorrect">
            <i class="fa-solid fa-xmark"></i>
            {{ incorrectAnswers }}
        </div>
    </div>
</div>
<app-learning-finished-modal *ngIf="setService.showLearningFinishedModal === true"></app-learning-finished-modal>
