// flashcards-react/src/pages/sets-list/sets-list.tsx
import React, { useState, useEffect } from 'react';
import styles from './sets-list.module.css'; 
import SingleSetComponent from '../../components/single-set/single-set';
import Navbar from '../../components/navbar/navbar';
import '@fortawesome/fontawesome-free/css/all.min.css';
import { getAllSetsByUserId } from '../../services/set-service';
import AddSetModal from '../../components/modals/set/add-set-modal/add-set-modal';


interface Set {
    setId: string;
    setName: string;
    createdAt: string;
    updatedAt: string;
    flashcardCount: number;
}

const SetsListComponent = () => {
    const [sets, setSets] = useState<Set[]>([]);
    const [filterText, setFilterText] = useState<string>('');
    const [showAddSetModal, setShowAddSetModal] = useState<boolean>(false);
    

    useEffect(() => {
        fetchSets();
    }, []);

    const fetchSets = async () => {
        try {
            const userId = localStorage.getItem('userId'); 

            if (!userId) {
                console.log('User is not logged in');
                return;
            }

            let fetchedSets = await getAllSetsByUserId(userId);
            fetchedSets = fetchedSets.sort(
                (a: { setName: string; }, b: { setName: string; }) => a.setName.localeCompare(b.setName)
            );
            setSets(fetchedSets);
        } catch (error: any) {
            console.log(error)
        } 
    };

    const filteredSets = sets.filter(set => set.setName.toLowerCase().includes(filterText.toLowerCase()));

    const handleFilterChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setFilterText(e.target.value);
    };

    const openAddSetModal = () => {
        setShowAddSetModal(true);
    };

    const closeAddSetModal = () => {
        setShowAddSetModal(false);
    };

    const refreshSetsList = () => {
        fetchSets();
    };

    return (
        <>
            <Navbar/>
            <div className={styles.setsListContainer}>
                <h2>Dostępne zbiory fiszek</h2>
                <div className={styles.filterContainer}>
                    <i className="fa-solid fa-magnifying-glass"></i>
                    <input type="text" placeholder="Filtruj zbiory" value={filterText} onChange={handleFilterChange} />
                </div>
                <div className={styles.setsList}>
                    <button className={styles.addButton} onClick={openAddSetModal}>
                        Dodaj zbiór&nbsp;
                        <i className="fa-solid fa-plus fa-sm"></i>
                        </button>
                    {filteredSets.map(set => (
                        <SingleSetComponent key={set.setId} setObj={set} refreshSetsList={refreshSetsList}/>
                    ))}
                </div>
            </div>
            {showAddSetModal && <AddSetModal closeAddSetModal={closeAddSetModal} refreshSetsList={refreshSetsList} />}
        </>
        
    );
};

export default SetsListComponent;

// flashcards-angular/src/app/pages/sets-list/sets-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SetService } from 'src/app/services/set.service';
import { SingleSetComponent } from 'src/app/components/single-set/single-set.component';
import { FormsModule } from '@angular/forms';
import { AddSetModalComponent } from 'src/app/components/modals/set/add-set-modal/add-set-modal.component';

@Component({
  selector: 'app-sets-list',
  standalone: true,
  imports: [CommonModule, FormsModule, SingleSetComponent, AddSetModalComponent],
  templateUrl: './sets-list.component.html',
  styleUrls: ['./sets-list.component.css'],
  providers: [SetService]
})
export class SetsListComponent implements OnInit{
  listOfSets: Array<any> = [];
  filteredSets: Array<any> = [];
  filterText: string = '';
  constructor(public setService: SetService) {
    const userId = localStorage.getItem('userId') || "";
    this.getAllSetsByUserId(userId);
  }
  ngOnInit(): void {
  }

  getAllSetsByUserId(userId: string) {
    this.setService.getAllSetsByUserId(userId)
      .subscribe({
        next: (res) => {
          this.listOfSets = res.sort(
            (a: { setName: string; }, b: { setName: string; }) => a.setName.localeCompare(b.setName)
          );
          this.filteredSets = [...this.listOfSets];
        },
        error: (err) => {
          console.error('Failed to load sets', err);
        }
      });
  }

  filterSets() {
    this.filteredSets = this.listOfSets.filter(set => 
      set.setName && set.setName.toLowerCase().includes(this.filterText.toLowerCase())
    );
  }

  editSet() {
    // logika do edycji zestawu
  }
  
  
  addSet() {
    this.setService.showAddSetModal = true;
  }

  refreshList() {
    const userId = localStorage.getItem('userId') || "";
    this.getAllSetsByUserId(userId);  // Załóżmy, że "1" to ID użytkownika
  }
}

<app-navbar></app-navbar>
<div class="main">
    <h2>Dostępne zbiory fiszek</h2>

    <div class="filter-container">
        <i class="fa-solid fa-magnifying-glass"></i>
        <input type="text" 
        placeholder="Filtruj zbiory" 
        [(ngModel)]="filterText" (input)="filterSets()" />
    </div>
    <div class="sets-list">
        <button class="add-button" (click)="addSet()">
            Dodaj zbiór
            <i class="fa-solid fa-plus fa-sm"></i>
        </button>
        <div *ngFor="let set of filteredSets">
            <app-single-set [setObj]="set" (onUpdate)="refreshList()" (onDelete)="refreshList()"></app-single-set>
        </div>
    </div>
</div>
<app-add-set-modal *ngIf="setService.showAddSetModal" (onAdd)="refreshList()"></app-add-set-modal>
