// flashcards-react/src/components/modals/flashcard/delete-flashcard-confirmation/delete-flashcard-confirmation-modal.tsx
import React from 'react';
import styles from './delete-flashcard-confirmation-modal.module.css';
import { deleteFlashcard } from '../../../../services/flashcard-service'; 

interface DeleteFlashcardConfirmationModalProps {
    closeDeleteFlashcardModal: () => void;
    refreshFlashcardsList: () => void;
    flashcardObj: {
        flashcardId: string;
        front: string;
    };
}

const DeleteFlashcardConfirmationModal: React.FC<DeleteFlashcardConfirmationModalProps> = ({ closeDeleteFlashcardModal, refreshFlashcardsList, flashcardObj }) => {
    
    const handleDelete = async () => {
        try {
            await deleteFlashcard(flashcardObj.flashcardId);
            refreshFlashcardsList();
            closeDeleteFlashcardModal();
        } catch (error) {
            console.error("Error deleting flashcard:", error);
        }
    };

    return (
        <>
            <div className={styles.overlay} onClick={closeDeleteFlashcardModal}></div>
            <div className={styles.deleteFlashcardModalContainer}>
                <div className={styles.header}>Usuwanie fiszki</div>
                <div className={styles.content}>
                    Czy na pewno chcesz usunąć fiszkę <i>{flashcardObj.front}</i>?
                </div>
                <div className={styles.actions}>
                    <button onClick={handleDelete}>Usuń</button>
                    <button onClick={closeDeleteFlashcardModal}>Anuluj</button>
                </div>
            </div>
        </>
    );
};

export default DeleteFlashcardConfirmationModal;

// flashcards-angular/src/app/components/modals/flashcard/delete-flashcard-confirmation-modal/delete-flashcard-confirmation-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SetService } from 'src/app/services/set.service';
import { FlashcardService } from 'src/app/services/flashcard.service';

@Component({
  selector: 'app-delete-flashcard-confirmation-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './delete-flashcard-confirmation-modal.component.html',
  styleUrls: ['./delete-flashcard-confirmation-modal.component.css'],
  providers: [FlashcardService]
})
export class DeleteFlashcardConfirmationModalComponent {
  @Input() flashcardObj: any;
  @Output() onDelete = new EventEmitter(); 
  @Output() onDeleteCancel = new EventEmitter();

  constructor(public flashcardService: FlashcardService) { }

  deleteFlashcard() {
    this.flashcardService.deleteFlashcard(this.flashcardObj.flashcardId).subscribe({
      next: (res) => {
        this.flashcardService.showDeleteFlashcardConfirmationModal = false;
        this.onDelete.emit();
        console.log("Flashcard deleted successfully");
      },
      error: (err) => {
        console.log(err);
      }
    });
  }

  deleteCancelAction() {
    console.log("CANCEL");
    this.onDeleteCancel.emit();
    this.flashcardService.showDeleteFlashcardConfirmationModal=false;
  }
}

<div id="overlay" (click)="deleteCancelAction()"></div>
<div id="container">
    <div id="header">Usuwanie fiszki</div>
    <div id="content">
        Czy na pewno chcesz usunąć fiszkę <i>{{ flashcardObj.front }}</i>?
    </div>
    <div id="actions">
        <button (click)="deleteFlashcard()" class="btn btn-custom">Usuń</button>
        <button (click)="deleteCancelAction()" class="cancel btn">Anuluj</button>
    </div>
</div>
