// flashcards-react/src/pages/flashcards-list/flashcards-list.tsx
import React, { useEffect, useState } from 'react';
import { useParams,  useNavigate } from 'react-router-dom'; 
import styles from './flashcards-list.module.css'; 
import Navbar from '../../components/navbar/navbar';
import '@fortawesome/fontawesome-free/css/all.min.css';
import SingleFlashcardComponent from '../../components/single-flashcard/single-flashcard';
import { getAllFlashcardsBySetId, getSetById } from '../../services/set-service'; 
import AddFlashcardModal from '../../components/modals/flashcard/add-flashcard-modal/add-flashcard-modal';


interface Flashcard {
  flashcardId: string;
  front: string;
  back: string;
}

interface Set {
  setId: string;
  setName: string;
  flashcardCount: number;
}

const FlashcardsListComponent = () => {
  const { setId } = useParams();
  const navigate = useNavigate(); 
  const [flashcards, setFlashcards] = useState<Flashcard[]>([]);
  const [setDetails, setSetDetails] = useState<Set | null>(null);
  const [filterText, setFilterText] = useState<string>('');
  const [showAddFlashcardModal, setShowAddFlashcardModal] = useState<boolean>(false); 

  useEffect(() => {
    if (setId) {  
      fetchFlashcards(setId); 
      fetchSetDetails(setId);
    }
  }, [setId]);

  const fetchFlashcards = async (id: string) => {
    try {
      let fetchedFlashcards = await getAllFlashcardsBySetId(id); 
      fetchedFlashcards = fetchedFlashcards.sort(
        (a: { front: string; }, b: { front: string; }) => a.front.localeCompare(b.front)
      );
      setFlashcards(fetchedFlashcards); 
    } catch (error) {
      console.error("Error fetching flashcards:", error); 
    }
  };

  const fetchSetDetails = async (id: string) => {
    try {
      const fetchedSet = await getSetById(id);
      setSetDetails(fetchedSet);
    } catch (error) {
      console.error("Error fetching set details:", error); 
    }
  };


  const filteredFlashcards = flashcards.filter(flashcard =>
      flashcard.front.toLowerCase().includes(filterText.toLowerCase())
  );

  const navigateToLearn = () => {
    if (setId) {
      navigate(`/sets/${setId}/learn`); 
    }
  };


  const openAddFlashcardModal = () => { 
    setShowAddFlashcardModal(true);
  };

  const closeAddFlashcardModal = () => { 
    setShowAddFlashcardModal(false);
  };

  const refreshFlashcardsList = () => {
    fetchFlashcards(setId!);
};

  return (
    <>
      <Navbar/>
      <div className={styles.flashcardsListContainer}>
        <h2>Fiszki w zbiorze <i>{setDetails?.setName}</i> ({flashcards.length})</h2>

        <div className={styles.filterContainer}>
          <i className="fa-solid fa-magnifying-glass"></i>
          <input type="text" placeholder="Filtruj fiszki" />
        </div>

        <div className={styles.flashcardsList}>
          <div className={styles.actions}>
            <button className={styles.learnButton} onClick={navigateToLearn} disabled={flashcards.length===0}>
              Tryb nauki&nbsp;
              <i className="fa-solid fa-graduation-cap"></i>
            </button>
            <button className={styles.addButton} onClick={openAddFlashcardModal}>
              Dodaj fiszki&nbsp;
              <i className="fa-solid fa-plus fa-sm"></i>
            </button>
          </div>
          {filteredFlashcards.map(flashcard => (
              <SingleFlashcardComponent
                  key={flashcard.flashcardId}
                  flashcardObj={flashcard}
                  refreshFlashcardsList={refreshFlashcardsList}
              />
          ))}
        </div>
      </div>
      {showAddFlashcardModal && 
        <AddFlashcardModal 
          closeAddFlashcardModal={closeAddFlashcardModal} 
          refreshFlashcardList={refreshFlashcardsList} 
        />
      }
    </>
  );
};

export default FlashcardsListComponent;

// flashcards-angular/src/app/pages/flashcards-list/flashcards-list.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SetService } from 'src/app/services/set.service';
import { ActivatedRoute, Router } from '@angular/router';
import { SingleFlashcardComponent } from 'src/app/components/single-flashcard/single-flashcard.component';
import { FormsModule } from '@angular/forms';
import { AddFlashcardModalComponent } from 'src/app/components/modals/flashcard/add-flashcard-modal/add-flashcard-modal.component';
import { FlashcardService } from 'src/app/services/flashcard.service';
import { NavbarComponent } from 'src/app/components/navbar/navbar.component';

@Component({
  selector: 'app-flashcards-list',
  standalone: true,
  imports: [
    CommonModule, 
    FormsModule, 
    NavbarComponent,
    SingleFlashcardComponent, 
    AddFlashcardModalComponent
  ],
  templateUrl: './flashcards-list.component.html',
  styleUrls: ['./flashcards-list.component.css'],
  providers: [SetService, FlashcardService]
})
export class FlashcardsListComponent {
  set: any = "";
  setFlashcards: Array<any> = [];
  filteredFlashcards: Array<any> = [];
  filterText: string = ''; 
  setId!: string;

  constructor(
    public flashcardService: FlashcardService, 
    private setService: SetService, 
    private router: Router,
    private activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.paramMap.subscribe(params => {
      this.setId = params.get('setId') ?? '';
      this.getSetById(this.setId);
      this.getAllFlashcardsBySetId(this.setId);
    });
  }


  getSetById(setId: string) {
    this.setService.getSetById(setId).subscribe({
      next: (res) => {
        this.set = res;
      },
      error: (err) => {
        console.log(err);
      }
    });
  }

  getAllFlashcardsBySetId(setId: string) {
    this.setService.getAllFlashcardsBySetId(setId).subscribe({
      next: (res) => {
        this.setFlashcards = res.sort(
          (a: { front: string; }, b: { front: string; }) => a.front.localeCompare(b.front)
        ); 
        this.filteredFlashcards = [...this.setFlashcards];
        console.log(this.setFlashcards);

      },
      error: (err) => {
        console.log(err);
      }
    });
  }
  
  filterFlashcards() {
    this.filteredFlashcards = this.setFlashcards.filter(flashcard =>
      flashcard.front.toLowerCase().includes(this.filterText.toLowerCase()) ||
      flashcard.back.toLowerCase().includes(this.filterText.toLowerCase())
    );
    console.log(this.filteredFlashcards)
  }

  addFlashcard() {
    this.flashcardService.showAddFlashcardModal = true;
  }

  openLearnMode() {
    this.router.navigate(['/sets', this.setId, 'learn']);
  }
  

  refreshList() {
    this.getSetById(this.setId);
    this.getAllFlashcardsBySetId(this.setId);  
  }
}

<app-navbar></app-navbar>
<div class="main">
  <h2>Fiszki w zbiorze <i>{{ set.setName }}</i>  ({{ set.flashcardCount}})</h2>
  <div class="filter-container">
    <i class="fa-solid fa-magnifying-glass"></i>
    <input type="text" placeholder="Filtruj fiszki" [(ngModel)]="filterText" (input)="filterFlashcards()" />
  </div>
  <div class="flashcards-list">
    <div class="actions">
      <button class="learn-button" (click)="openLearnMode()" [disabled]="set.flashcardCount === 0">
        Tryb nauki
        <i class="fa-solid fa-graduation-cap"></i>
      </button>
  
      <button class="add-button" (click)="addFlashcard()">
        Dodaj fiszki
        <i class="fa-solid fa-plus fa-sm"></i>
      </button>
    </div>
    
    
    <div *ngFor="let flashcard of filteredFlashcards">
      <app-single-flashcard [flashcardObj]="flashcard" (onUpdate)="refreshList()" (onDelete)="refreshList()" (onDeleteCancel)="refreshList()"></app-single-flashcard>
    </div>
  </div>
</div>
<app-add-flashcard-modal *ngIf="flashcardService.showAddFlashcardModal" (onAdd)="refreshList()"></app-add-flashcard-modal>
