// flashcards-angular/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { NavbarComponent } from 'src/app/components/navbar/navbar.component';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, NavbarComponent],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  providers: [AuthService]
})
export class HomeComponent implements OnInit {

  isUserLoggedIn: boolean = false;

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.isUserLoggedIn = this.authService.isLoggedIn();
  }

  goToSets() {
    this.router.navigate(['sets']);
  }
}

<app-navbar></app-navbar>
<div class="main">
    <h1><i>Witaj w aplikacji FlashLearn!</i></h1>
    <p>
        Witamy w naszej aplikacji do nauki języków obcych (i nie tylko) za pomocą fiszek!
        Aplikacja ta została stworzona, aby pomóc Ci w skutecznym przyswajaniu 
        nowego słownictwa, pojęć oraz rozwijaniu umiejętności zapamiętywania. Dzięki niej możesz 
        dodawać nowe fiszki, edytować istniejące, a także usuwać te, które nie są Ci już 
        potrzebne. 
        Zapraszamy do korzystania z naszej aplikacji i życzymy owocnej nauki języków obcych!
    </p>
    <button *ngIf="isUserLoggedIn" (click)="goToSets()">Do zbiorów!</button>
</div>

// flashcards-react/src/pages/home/home.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import styles from './home.module.css'; 
import Navbar from '../../components/navbar/navbar';
import {getLoggedInUserId} from '../../services/auth-service';

const HomeComponent = () => {

  const navigate = useNavigate(); 

  const goToSets = () => {
    navigate('/sets'); 
  };

  return (
    <>
        <Navbar/>
        <div className={styles.homeContainer}>
            <h1><i>Witaj w aplikacji FlashLearn!</i></h1>
            <p>
                Witamy w naszej aplikacji do nauki języków obcych (i nie tylko) za pomocą fiszek!
                Aplikacja ta została stworzona, aby pomóc Ci w skutecznym przyswajaniu 
                nowego słownictwa, pojęć oraz rozwijaniu umiejętności zapamiętywania. Dzięki niej możesz 
                dodawać nowe fiszki, edytować istniejące, a także usuwać te, które nie są Ci już 
                potrzebne. 
                Zapraszamy do korzystania z naszej aplikacji i życzymy owocnej nauki języków obcych!
            </p>
            {
              getLoggedInUserId() && <button onClick={goToSets}>Do zbiorów!</button>
            }
        </div>

    </>
  );
};

export default HomeComponent;
