// flashcards-angular/src/app/pages/auth/registration/registration.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';

@Component({
  selector: 'app-registration',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.css']
})
export class RegistrationComponent {
  registrationForm!: FormGroup;

  constructor(
    private router: Router,
    private formBuilder: FormBuilder,
  ) { }

  ngOnInit(): void {
    this.registrationForm = this.formBuilder.group({
      firstName: ['', Validators.required],
      lastName: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      phoneNumber: ['', [
        Validators.required, 
        Validators.pattern('[- +()0-9]{9,12}')
      ]],
      password: ['', [
        Validators.required, 
        Validators.pattern(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[~!@#$%^&*()+=<>?])[A-Za-z\d~!@#$%^&*()+=<>?]{8,}$/)
      ]],
      confirmPassword: ['', Validators.required],
    }
    );
  }

  register() {
    console.log("register fun()");
    console.log(this.registrationForm.value);
  }
}

<div class="content">
    <div class="registration">
        <h2 class="">Rejestracja</h2>
    
    <form [formGroup]="registrationForm">

        <div class="field">
            <input type="text" formControlName="firstName" class="form-control" placeholder="Imię">
            <span *ngIf="registrationForm.controls['firstName'].errors?.['required'] && (registrationForm.controls['firstName'].dirty || registrationForm.controls['firstName'].touched)" class="text-danger" >
                *Imię jest wymagane.
            </span>     
        </div>

        <div class="field">
            <input type="text" formControlName="lastName" class="form-control" placeholder="Nazwisko">
            <span *ngIf="registrationForm.controls['lastName'].errors?.['required'] && (registrationForm.controls['lastName'].dirty || registrationForm.controls['lastName'].touched)" class="text-danger" >
                *Nazwisko jest wymagane.
            </span>    
        </div>

        
        <div class="field">
            <input type="text" formControlName="email" class="form-control" placeholder="Email">
            <span *ngIf="registrationForm.controls['email'].errors?.['required'] && (registrationForm.controls['email'].dirty || registrationForm.controls['email'].touched)" class="text-danger" >
                *Email jest wymagany.
            </span>    
            <span *ngIf="registrationForm.controls['email'].errors?.['email']  && registrationForm.controls['email'].touched" class="text-danger">
                *Email jest niepoprawny.
            </span>  
        </div>
        <div class="field">
            <input type="text" formControlName="phoneNumber" class="form-control" placeholder="Telefon">
            <span *ngIf="registrationForm.controls['phoneNumber'].errors?.['required'] && (registrationForm.controls['phoneNumber'].dirty || registrationForm.controls['phoneNumber'].touched)" class="text-danger">
                *Numer telefonu jest wymagany.
            </span>    
            <span *ngIf="registrationForm.controls['phoneNumber'].errors?.['pattern']  && registrationForm.controls['phoneNumber'].touched" class="text-danger">
                *Numer telefonu jest niepoprawny.
            </span>  
        </div>

        <div class="field">
            <input type="password" formControlName="password" class="form-control" placeholder="Hasło">
            <span *ngIf="registrationForm.controls['password'].errors?.['required'] && (registrationForm.controls['password'].dirty || registrationForm.controls['password'].touched)" class="text-danger" >
                *Hasło jest wymagane.
            </span>    
        </div>
        <div class="field">
            <input type="password" formControlName="confirmPassword" class="form-control" placeholder="Potwierdź hasło">
            <span *ngIf="registrationForm.controls['confirmPassword'].errors?.['required'] && (registrationForm.controls['confirmPassword'].dirty || registrationForm.controls['confirmPassword'].touched)" class="text-danger" >
                *Potwierdzenie hasła jest wymagane.
            </span>    
        </div>
        
        <div class="form-actions">
            <button (click)="register()" [disabled]="!registrationForm.valid" type="button" class="btn btn-custom">Zarejestruj się</button>
            <div class="a-container">
               Masz już konto?<a routerLink="/login" class="text-decoration-none" href="">Zaloguj się</a>
            </div>
        </div>
    </form>
    </div>
    
</div>

// flashcards-react/src/pages/auth/registration/registration.tsx
import React, { useState, FormEvent } from 'react';
import { Link } from 'react-router-dom';
import './registration.css'; // Import your styles

interface FormErrors {
    firstName: string;
    lastName: string;
    email: string;
    phoneNumber: string;
    password: string;
    confirmPassword: string;
}

const RegistrationComponent = () => {
    const [formData, setFormData] = useState({
        firstName: '',
        lastName: '',
        email: '',
        phoneNumber: '',
        password: '',
        confirmPassword: ''
    });
    const [errors, setErrors] = useState<FormErrors>({
        firstName: '',
        lastName: '',
        email: '',
        phoneNumber: '',
        password: '',
        confirmPassword: ''
    });

    const validateForm = (): boolean => {
        let valid = true;
        const newErrors: FormErrors = {
            firstName: '',
            lastName: '',
            email: '',
            phoneNumber: '',
            password: '',
            confirmPassword: ''
        };

        if (!formData.firstName) {
            newErrors.firstName = '*Imię jest wymagane.';
            valid = false;
        }

        if (!formData.lastName) {
            newErrors.lastName = '*Nazwisko jest wymagane.';
            valid = false;
        }

        if (!formData.email) {
            newErrors.email = '*Email jest wymagany.';
            valid = false;
        } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
            newErrors.email = '*Email jest niepoprawny.';
            valid = false;
        }

        if (!formData.phoneNumber) {
            newErrors.phoneNumber = '*Numer telefonu jest wymagany.';
            valid = false;
        }

        if (!formData.password) {
            newErrors.password = '*Hasło jest wymagane.';
            valid = false;
        }

        if (formData.confirmPassword !== formData.password) {
            newErrors.confirmPassword = '*Hasła nie są takie same.';
            valid = false;
        }

        setErrors(newErrors);
        return valid;
    };

    const handleSubmit = (e: FormEvent<HTMLFormElement>): void => {
        e.preventDefault();
        if (validateForm()) {
            console.log('Registration data:', formData);
            // Handle registration logic here, possibly involving an API call
        }
    };

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    return (
        <div className="content">
            <div className="registration">
                <h2>Rejestracja</h2>
                <form onSubmit={handleSubmit}>
                    <div className="field">
                        <input type="text" name="firstName" className="form-control" placeholder="Imię" value={formData.firstName} onChange={handleChange} />
                        {errors.firstName && <span className="text-danger">{errors.firstName}</span>}
                    </div>
                    <div className="field">
                        <input type="text" name="lastName" className="form-control" placeholder="Nazwisko" value={formData.lastName} onChange={handleChange} />
                        {errors.lastName && <span className="text-danger">{errors.lastName}</span>}
                    </div>
                    <div className="field">
                        <input type="text" name="email" className="form-control" placeholder="Email" value={formData.email} onChange={handleChange} />
                        {errors.email && <span className="text-danger">{errors.email}</span>}
                    </div>
                    <div className="field">
                        <input type="text" name="phoneNumber" className="form-control" placeholder="Telefon" value={formData.phoneNumber} onChange={handleChange} />
                        {errors.phoneNumber && <span className="text-danger">{errors.phoneNumber}</span>}
                    </div>
                    <div className="field">
                        <input type="password" name="password" className="form-control" placeholder="Hasło" value={formData.password} onChange={handleChange} />
                        {errors.password && <span className="text-danger">{errors.password}</span>}
                    </div>
                    <div className="field">
                        <input type="password" name="confirmPassword" className="form-control" placeholder="Potwierdź hasło" value={formData.confirmPassword} onChange={handleChange} />
                        {errors.confirmPassword && <span className="text-danger">{errors.confirmPassword}</span>}
                    </div>
                    <div className="form-actions">
                        <button type="submit" className="btn btn-custom">Zarejestruj się</button>
                        <div className="a-container">
                            <p>Masz już konto?</p>
                            <Link to="/login" className="register-link">Zaloguj się</Link>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default RegistrationComponent;
