// flashcards-react/src/pages/page-not-found/page-not-found.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import styles from './page-not-found.module.css'; 
import Navbar from '../../components/navbar/navbar';

const PageNotFoundComponent = () => {
  return (
    <>
      <Navbar/>
      <div className={styles.pageNotFoundContainer}>
        <h1>404</h1>
        <p>Strona, której szukasz, nie została znaleziona.</p>
        <Link to="/" className={styles.mainPageLink}>Powrót do strony głównej</Link>
      </div>
    </>
  );
};

export default PageNotFoundComponent;

// flashcards-angular/src/app/pages/page-not-found/page-not-found.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { NavbarComponent } from 'src/app/components/navbar/navbar.component';

@Component({
  selector: 'app-page-not-found',
  standalone: true,
  imports: [
    CommonModule, 
    RouterModule,
    NavbarComponent
  ],
  templateUrl: './page-not-found.component.html',
  styleUrls: ['./page-not-found.component.css']
})
export class PageNotFoundComponent {

}

<app-navbar></app-navbar>
<div class="page-not-found-container">
    <h1>404</h1>
    <p>Strona, której szukasz, nie została znaleziona.</p>
    <a routerLink="/">Powrót do strony głównej</a>
</div>
