// flashcards-angular/src/app/pages/auth/login/login.component.ts
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from 'src/app/services/auth.service';
import { NavbarComponent } from 'src/app/components/navbar/navbar.component';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule, 
    NavbarComponent,
    ReactiveFormsModule, 
    RouterModule
  ],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  providers: [AuthService]
})
export class LoginComponent implements OnInit{
  
  loginForm!: FormGroup;

  constructor(
    private authService: AuthService,
    private router: Router,
    private formBuilder: FormBuilder,
    private cdr: ChangeDetectorRef
  ) { }

  ngOnInit(): void {
    this.loginForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
    });
  }

  login() {
    this.authService.loginService(this.loginForm.value)
    .subscribe({
      next: (res) => {
        this.authService.login(res.userId)
          this.router.navigate(['']);
      },
      error: (err) => {
        console.log(err);
        this.loginForm.reset();
        this.router.navigate(['login']);
    }});
  }
}

<app-navbar></app-navbar>
<div class="content">
    <div class="login">
        <h2 class="">Logowanie</h2>
    
    <form [formGroup]="loginForm">
        
        <div class="field">
            <input type="text" formControlName="email" class="form-control" placeholder="Email">
            <span *ngIf="loginForm.controls['email'].errors?.['required'] && (loginForm.controls['email'].dirty || loginForm.controls['email'].touched)" class="form-error" >
                *Email jest wymagany.
            </span>    
            <span *ngIf="loginForm.controls['email'].errors?.['email']  && loginForm.controls['email'].touched" class="form-error">
                *Email jest niepoprawny.
            </span>  
        </div>
        <div class="field">
            <input type="password" formControlName="password" class="form-control" placeholder="Hasło">
            <span *ngIf="loginForm.controls['password'].errors?.['required'] && (loginForm.controls['password'].dirty || loginForm.controls['password'].touched)" class="form-error">
                *Hasło jest wymagane.
            </span>    
        </div>
        
        <div class="form-actions">
            <button (click)="login()" [disabled]="loginForm.invalid" type="button" class="btn btn-custom">Zaloguj się</button>
            <div class="a-container">
                <p>Nie masz konta?</p>
                <a routerLink="/register"  href="">Zarejestruj się</a>
            </div>
        </div>
    </form>
    </div>
    
</div>

// flashcards-react/src/pages/auth/login/login.tsx
import React from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import Navbar from '../../../components/navbar/navbar';
import { loginService, login } from '../../../services/auth-service';
import styles from './login.module.css';
import { validateLoginField } from '../../../validators/validators';

interface LoginFormValues {
    email: string;
    password: string;
}

const LoginComponent = () => {
    const navigate = useNavigate();
    const {
        register,
        handleSubmit,
        formState: { errors, touchedFields, dirtyFields, isValid, isSubmitting },
        setError,
        clearErrors
    } = useForm<LoginFormValues>({
        mode: 'onChange',
        
    });


    const onSubmit = async (data: LoginFormValues) => {
        try {
            const response = await loginService(data);
            login(response.userId);
            navigate('/');
        } catch (err) {
            console.error('Login error:', err);
        }
    };

    const isSubmitButtonDisabled = () => {
        return !isValid || isSubmitting || !!errors.email || !!errors.password;
    };

    return (
        <>
            <Navbar />
            <div className={styles.loginContainer}>
                <div className={styles.login}>
                    <h2>Logowanie</h2>
                    <form onSubmit={handleSubmit(onSubmit)}>
                        <div className={styles.field}>
                            <input
                                type="text"
                                placeholder="Email"
                                {...register('email', {
                                    required: '*Email jest wymagany.',
                                    onChange: (e) => validateLoginField('email', e.target.value, setError, clearErrors),
                                    onBlur: (e) => validateLoginField('email', e.target.value, setError, clearErrors)
                                })}
                            />
                            {errors.email && (touchedFields.email || dirtyFields.email) && (
                                <span className="formError">{errors.email.message}</span>
                            )}
                        </div>
                        <div className={styles.field}>
                            <input
                                type="password"
                                placeholder="Hasło"
                                {...register('password', {
                                    required: '*Hasło jest wymagane.',
                                    onChange: (e) => validateLoginField('password', e.target.value, setError, clearErrors),
                                    onBlur: (e) => validateLoginField('password', e.target.value, setError, clearErrors)
                                })}
                            />
                            {errors.password && (touchedFields.password || dirtyFields.password) && (
                                <span className="formError">{errors.password.message}</span>
                            )}
                        </div>
                        <div className={styles.formActions}>
                            <button
                                type="submit"
                                className={styles.loginButton}
                                disabled={isSubmitButtonDisabled()}
                            >
                                Zaloguj się
                            </button>
                            <div className={styles.linkContainer}>
                                <p>Nie masz konta?</p>
                                <Link to="/register" className={styles.registerLink}>Zarejestruj się</Link>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </>
    );
};

export default LoginComponent;
