// flashcards-react/src/components/navbar/navbar.tsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import './navbar.css';  // Upewnij się, że plik CSS jest dołączony
import logo from '../../assets/images/logo.png'; 

const Navbar = () => {
    const [navbarOpen, setNavbarOpen] = useState(false);

    const toggleNavbar = () => {
        setNavbarOpen(!navbarOpen);
    };

    return (
        <nav className="navbar">
            <div className="navbar-container">
                <Link to="/" className="navbar-logo">
                    <img src={logo} alt="Logo" />

                </Link>
                <button className="navbar-toggler" onClick={toggleNavbar}>Menu</button>
                <div className={`navbar-links ${navbarOpen ? 'active' : ''}`}>
                    <Link to="/about">O aplikacji</Link>
                    <Link to="/login">Logowanie</Link>
                    <Link to="/register">Rejestracja</Link>
                </div>
            </div>
        </nav>
    );
};

export default Navbar;

// flashcards-angular/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {
  navbarOpen = false;


  constructor(
    private router: Router
  ) { }


  toggleNavbar() {
    this.navbarOpen = !this.navbarOpen;
  }

  logout() {
    localStorage.removeItem('userId');
    this.router.navigate(['/login']);
  }

}

<nav class="navbar">
    <div class="navbar-container">
      <a href="/" class="navbar-logo">
        <img src="assets/images/logo.png" alt="Logo">
      </a>
      <button class="navbar-toggler" (click)="toggleNavbar()">Menu</button>
      <div class="navbar-links" [class.active]="navbarOpen">
      <!--<a href="/">Strona Główna</a> -->
      <a href="/about">O aplikacji</a>
      <a href="/login">Logowanie</a>
      <a href="/register">Rejestracja</a>
    </div>
    </div>
  </nav>
